### ISSUE TITLE
SyntaxError: Unexpected token e

### ISSUE THREAD

**Issue by Gokuref** [niobio-cash/forknote-pool#4]
Fala moçada!  Estou com um erro aqui que está impedindo a minha "pool test" de rodar...

erro abaixo:
> 2018-03-09 13:47:04 [master] Pool fork 3 died, spawning replacement worker...
> 2018-03-09 13:47:04 [pool] (Thread 2) Error storing scratchpad: {"code":-32601,"message":"Method not found"}
> SyntaxError: Unexpected token e
>     at Object.parse (native)
>     at /home/pc/pool/lib/pool.js:110:23
>     at /home/pc/pool/lib/apiInterfaces.js:107:9
>     at IncomingMessage.<anonymous> (/home/pc/pool/lib/apiInterfaces.js:71:13)
>     at IncomingMessage.emit (events.js:117:20)
>     at _stream_readable.js:944:16
>     at process._tickCallback (node.js:458:13)
> 

Alguma luz?

**Comment by Gokuref** [comment]
Resolvido! 
Eu estava usando node --version = 0.10.48. 

Fiz o seguinte:
Apaguei node_modules da pool, instalei node --version =0.10.25,  rodei novamente npm update, e agora o node init.js não apresenta mais erros.
Vou fazer alguns testes, e estando tudo ok, colocarei online e mandarei o link pra vcs...
Abrçs!
